### ISSUE TITLE
Process new datasets

### ISSUE THREAD

**Issue by taharallouche** [taharallouche/hakeem#31]
### Description
The package as it is in the time being only works on three datasets mentionned in the paper. The methods should however be applicable to any  dataset of collectively annotated data.

### Suggested Changes
Implement and test new features to:
- [x] allow users to load their datasets (into a standard format).
- [x] test and apply the defined aggregation rules to these datasets.
- [x] save the output and report findings.

### Success Criteria
The package can handle new datasets of collectively labeled data.

### Contributors
@taharallouche @MohamedAmineChihi

**Comment by taharallouche** [comment]
We might design the interface with users as Jupyter notebooks. They shouldn't contain any logic though. All the logic should be in well tested and maintained scripts.
