### ISSUE TITLE
Isolate the paper results reproduction code in another repo

### ISSUE THREAD

**Issue by taharallouche** [taharallouche/hakeem#48]
### Description
The goal of this epic is to isolate the code for AAAI resutls reproduction into another repo, that can use the features of this repo. To do so, crowd-label-py needs to be packaged and pip-installable.

### Suggested Changes
- [x] Identify the results reproduction code to be migrated.
- [x] Make the crowd-label-py modules more dataset agnostic.
- [x] Package and realease crowd-label-py.
- [x] Move reproduction code into another repo that has crowd-label-py as a requirement.

### Success Criteria
AAAI paper results reproduction code is in another repo that uses features imported from crowd-label-py.

**Comment by taharallouche** [comment]
https://github.com/taharallouche/truth-tracking-aaai-2022
